### ISSUE TITLE
feature request: recognize tab character

### ISSUE THREAD

**Issue by c-nv-s** [areYouLazy/hosty#1]
**Is your feature request related to a problem? Please describe.**
At present if your hosts file only contains tab delimiters then the output of hosty's commands do not preserve the spacing and thus you receive a concatanated ip address with the hostname in the result.

**Describe the solution you'd like**
It would be nice for hosty to respect/preserve tab characters or replace them with a space when displaying results

**Describe alternatives you've considered**
Alternative is to force everyone to only use space separated entries in their hosts files.

**Comment by areYouLazy** [comment]
Can you provide more details to reproduce this? I've a lot of tabbed lines in my hosts file but cannot reproduce what you are talking about

**Comment by c-nv-s** [comment]
![hostytabbedentryissue](https://user-images.githubusercontent.com/7495833/122144774-601cb180-ce54-11eb-806f-780bfc414a12.gif)

**Comment by areYouLazy** [comment]
I see.
So first thing to note is that your file is not re-rendered because of the "show" action. Any other action (comment/uncomment/add/delete) will reformat your file to follow some advices: 16 chars are reserved for IP (123.123.123.123) than one \t is placed and than hostnames are appended to the line splitted by space.
This should ensures (more or less) a consistent file format and better readability

However your output shows an incorrect line parsing that I'm not able to reproduce on macOS (it seems to work as expected), let me get a Debian and try to reproduce this

**Comment by areYouLazy** [comment]
Ok, this is not a parsing error and only affects hosty CLI output because i trimmed `\t`chars that are correctly rendered in the hosts file but are printed as `\t`in the CLI output, so a show command would output something like this:
```console
root@localhost$ hosty show 1.2.3.4
1.2.3.4\tmy.tabbed.host
```
I'll switch from "trim" to "convert tab to spaces", however it would be cool to render the tabbed char in CLI output also
